//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telefonbok.KontaktService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KontaktService.ITelefonbokService")]
    public interface ITelefonbokService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelefonbokService/HämtaAllaKontakter", ReplyAction="http://tempuri.org/ITelefonbokService/HämtaAllaKontakterResponse")]
        System.Xml.Linq.XElement HämtaAllaKontakter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelefonbokService/LäggTillKontakt", ReplyAction="http://tempuri.org/ITelefonbokService/LäggTillKontaktResponse")]
        void LäggTillKontakt(System.Xml.Linq.XElement kontakt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelefonbokService/TaBortKontakt", ReplyAction="http://tempuri.org/ITelefonbokService/TaBortKontaktResponse")]
        void TaBortKontakt(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelefonbokService/ÄndraKontakt", ReplyAction="http://tempuri.org/ITelefonbokService/ÄndraKontaktResponse")]
        void ÄndraKontakt([System.ServiceModel.MessageParameterAttribute(Name="ändraKontakt")] System.Xml.Linq.XElement ändraKontakt1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelefonbokService/SökKontakter", ReplyAction="http://tempuri.org/ITelefonbokService/SökKontakterResponse")]
        System.Xml.Linq.XElement SökKontakter(System.Xml.Linq.XElement kriterier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITelefonbokServiceChannel : Telefonbok.KontaktService.ITelefonbokService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TelefonbokServiceClient : System.ServiceModel.ClientBase<Telefonbok.KontaktService.ITelefonbokService>, Telefonbok.KontaktService.ITelefonbokService {
        
        public TelefonbokServiceClient() {
        }
        
        public TelefonbokServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TelefonbokServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelefonbokServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelefonbokServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.Linq.XElement HämtaAllaKontakter() {
            return base.Channel.HämtaAllaKontakter();
        }
        
        public void LäggTillKontakt(System.Xml.Linq.XElement kontakt) {
            base.Channel.LäggTillKontakt(kontakt);
        }
        
        public void TaBortKontakt(int id) {
            base.Channel.TaBortKontakt(id);
        }
        
        public void ÄndraKontakt(System.Xml.Linq.XElement ändraKontakt1) {
            base.Channel.ÄndraKontakt(ändraKontakt1);
        }
        
        public System.Xml.Linq.XElement SökKontakter(System.Xml.Linq.XElement kriterier) {
            return base.Channel.SökKontakter(kriterier);
        }
    }
}
